# Use an official Python runtime as the base image
FROM python:3.9-slim

# Set a working directory
WORKDIR /app

# Install dbt core and any specific adapters you need (for example, dbt-postgres)
RUN pip install --no-cache-dir dbt-core dbt-bigquery

WORKDIR /app/sunshine_dbt